"use strict";
let lname;
let fname = 'aashish';
lname = "dahale";
let newname = fname.toUpperCase() + " " + lname.toUpperCase();
console.log(newname);
let age;
age = 25;
age = 25.5;
let dob = "25";
let result = parseInt(dob);
console.log(result);
let isValid = false;
console.log(isValid);
let empList;
empList = ["Aashish", "Aashish1", "Aashish2", "Aashish3"];
let numList;
numList = [1, 2, 3, 4, 5];
// let newNum = numList[5];
let results = numList.filter((num) => num > 2);
let num = numList.find((num) => num === 2);
let emp = empList.find((emp) => emp === "Aashish3");
let sum = numList.reduce((acc, num) => acc + num);
console.log(results);
console.log(num);
console.log(emp);
console.log(sum);
let c = 2 /* Color.Blue */;
let swapNumbs;
function swapNumbers(num1, num2) {
    return [num2, num1];
}
swapNumbs = swapNumbers(10, 20);
console.log(swapNumbs[0]);
console.log(swapNumbs[1]);
// swapNumbs[2];
let department;
department = "IT";
department = 10;
